### PR TITLE
Add function to get more information about userBrowser

### PR DESCRIPTION
**Pull request by vuquangpham**

### CODE REVIEW

**Comment by phucbm** [comment]
Please change the display like this:

View: [Body class](#), [HTML class](#)

Also, I don't want the underline here.

Screen Shot 2022-10-13 at 16 20 44

**Comment by vuquangpham** [comment]
> Please change the display like this:
> 
> View: [Body class](#), [HTML class](#)
> 
> Also, I don't want the underline here.
> 
> Screen Shot 2022-10-13 at 16 20 44

I have changed the style. Please check it again. Thanks !

**Comment by vuquangpham** [comment]
I have chosen the [ipify API](https://www.ipify.org/) because:
- It's an open-source [repository](https://github.com/rdegges/ipify-api)
- No limit requests per minute
- Its GitHub has more stars (over 1.3K)

**Review by phucbm — APPROVED** [review]
LGTM.

**Pull request merged**
