### PR TITLE
Add time feature for FE Debug

### PR DESCRIPTION
**Pull request by vuquangpham**

### CODE REVIEW

**Comment by vuquangpham** [comment]
More information about the upTime feature:
- The upTime script only runs when you turn on the debug on your website (like the way FEDebug works)
- You can go all the pages of your website (through pathName)
- I have checked the same website (to calculate the total time for accessing the page) by comparing the origin property (image below)

image

image

And that's all. So if you have a better way to make it, please let me know. Many thanks!

**Comment by phucbm** [comment]
The Uptime is good now, but we need to know "time on this page" too. Something like this:

Uptime: (total)
On this page: ...

Thanks.

**Comment by vuquangpham** [comment]
> The Uptime is good now, but we need to know "time on this page" too. Something like this:
> 
> Uptime: (total) On this page: ...
> 
> Thanks.

I have added time on particular page features. Please check it again!

**Review by phucbm — APPROVED** [review]
LGTM.

**Pull request merged**
